//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oblig4FrontDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservations
    {
        public int ReservationId { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int RoomNumber { get; set; }
        public string UserName { get; set; }
    
        public virtual rooms rooms { get; set; }
        public virtual users users { get; set; }
    }
}
